
// This file was generated by Prisma and assumes you have installed the
// following: npm install --save-dev prisma dotenv
if (process.env.NODE_ENV !== 'test') {
  await import('dotenv/config');
}
import {defineConfig, env} from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: env('DB_URL'),
  },
});
